baseURL = "https://yourusername.github.io/"
languageCode = "en-us"
title = "Hxx'Log"
theme = "PaperMod"

enableEmoji = true  # This enables emoji shortcodes

# Enable search
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  title = "Hxx'Log"
  description = "Brain dump and share my learnings here."
  author = "hxx"
  
  # PaperMod specific options
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
    
  [params.homeInfoParams]
    title = "Hi there! :wave:"
    content = "Hi, welcome to my blog! I'm hxx, a SWE/MLE fascinated by how everything works. This blog is my space to dump my learnings, mostly on LLM, maybe other stuff too."

    # For search
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]
    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/scoopxx"
  
#   [[params.socialIcons]]
#     name = "twitter"
#     url = "https://twitter.com/yourusername"


# Main menu configuration
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30
    
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 40
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50
  